/**
 * Stage-aware starter chip strings for the home screen (TASK-011).
 *
 * The strings live in this typed table and are NOT generated by an LLM —
 * three-string lists are easier to A/B and review with PM than prompt
 * engineering. PRD §6.2 / TASK-011 acceptance criteria.
 *
 * `null` is treated as `"early"` per TASK-011 ("If `inferStage(...) === 'early'` or `null`").
 */

import type { Stage } from "@alongside/rag";

export const STARTER_PROMPTS: Record<Stage, readonly [string, string, string]> = {
  early: [
    "She keeps asking the same question",
    "How do I talk about the diagnosis",
    "Do I need a power of attorney",
  ],
  middle: ["Afternoon agitation", "Bathing resistance", "Am I burning out"],
  late: [
    "Bathing resistance",
    "How to handle non-recognition",
    "When to consider memory care",
  ],
} as const;

export function startersForStage(stage: Stage | null): readonly [string, string, string] {
  return STARTER_PROMPTS[stage ?? "early"];
}
